# Generated by Django 4.1.6 on 2023-02-10 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sale_date", models.DateField(auto_now_add=True)),
                ("start_hour", models.DateTimeField(auto_now_add=True)),
                ("end_hour", models.DateTimeField(null=True)),
                ("brand", models.CharField(max_length=50)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cartão de Crédito", "Cc"),
                            ("Cartão de Débito", "Cd"),
                            ("PIX", "Pix"),
                            ("Dinheiro", "Dc"),
                        ],
                        default="Dinheiro",
                        max_length=50,
                    ),
                ),
                ("car_plate", models.CharField(max_length=7)),
                ("price_by_hour", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
