# Generated by Django 4.1.6 on 2023-02-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cartão de Crédito", "Credit"),
                    ("Cartão de Débito", "Debit"),
                    ("PIX", "Pix"),
                    ("Dinheiro", "Money"),
                ],
                default="Dinheiro",
                max_length=50,
            ),
        ),
    ]
