# Generated by Django 4.1.6 on 2023-02-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cartão de Crédito", "Cc"),
                    ("Cartão de Débito", "Cd"),
                    ("PIX", "Pix"),
                    ("Dinheiro", "Dc"),
                ],
                default="Dinheiro",
                max_length=50,
            ),
        ),
    ]
