# Generated by Django 4.1.6 on 2023-02-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_alter_sale_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="sale_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="start_hour",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
