# Generated by Django 4.1.6 on 2023-02-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_alter_sale_sale_date_alter_sale_start_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="end_hour",
            field=models.DateTimeField(null=True),
        ),
    ]
